name: Publish Docker
on:
  push:
  schedule:
    - cron: '0 2 * * 0' # Weekly on Sundays at 02:00
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Publish to Registry
      id: push
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: ameausoone/howdoi-docker-image/howdoi
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ghcr.io
    - name: Print docker image size
      run: docker image inspect ${{ steps.push.outputs.digest }} --format='{{.Size}}'